# The IAM role in the customer's own AWS account that Soroush assumes to run Bedrock
# inference on the customer's bill, in the customer's region.
#
# ## Why this is a module and not a block of JSON in the documentation
#
# A published IAM policy is a supply-chain artifact: whoever controls the text controls
# what a customer grants. Pasted JSON is reviewed once, by one person, at the moment it
# is pasted, and never again — there is no diff when it changes and no record of which
# version a given account is running.
#
# A module is reviewable in a `plan` and diffable on change, which is the reason this
# directory exists.
#
# ## Why the ARNs are read out of a file instead of written here
#
# `inference-role-arns.json` is generated by Soroush from the same table the API
# renders its published policy from. This module reads `regionWildcards` and the ARN
# grammar out of it verbatim and re-derives nothing, because the plausible
# re-derivation is wrong in a way that passes review: `apac` maps to `ap-*`, since AWS
# region names are `ap-southeast-1` and `ap-northeast-1` and there is no `apac-`
# region. A policy carrying `apac-*` deploys clean, plans clean, applies clean, and
# then denies at the first invocation. Reading the file means a geography Soroush adds
# is honoured without an edit here.

locals {
  # The single source. Read verbatim; nothing below re-derives any of it.
  arn_table = jsondecode(file("${path.module}/inference-role-arns.json"))

  arn_grammar         = local.arn_table.arn
  region_wildcards    = local.arn_table.regionWildcards
  geography_separator = local.arn_table.classification.geographySeparator

  # The CLOSED membership list, tested against before `region_wildcards` is ever
  # indexed, so that "is this a geography?" is a question about the file's list rather
  # than about whether a lookup happened to succeed.
  geographies = local.arn_table.geographies

  # `distinct`, matching the platform's own rendering: the same identifier as a
  # selection and as a pin is one grant, not two.
  profile_ids = distinct(var.profile_ids)

  # `separatorOccurrence` in the file is "first", so the first segment is everything
  # up to the first separator and the model id is everything after it.
  first_segment = { for id in local.profile_ids : id => split(local.geography_separator, id)[0] }

  # null means "no geography prefix": `unknownFirstSegmentIsProvider`, so the first
  # segment is a model provider (`amazon`, `anthropic`) and the whole identifier is a
  # bare foundation-model id.
  geography_of = {
    for id in local.profile_ids : id =>
    contains(local.geographies, local.first_segment[id]) ? local.first_segment[id] : null
  }

  model_id = {
    for id in local.profile_ids : id =>
    local.geography_of[id] == null
    ? id
    : substr(id, length(local.first_segment[id]) + length(local.geography_separator), -1)
  }

  customer_account_id = coalesce(
    var.customer_account_id,
    one(data.aws_caller_identity.current[*].account_id),
  )

  # One entry per ARN, in the order the policy must list them: for each identifier in
  # input order, the inference-profile ARN and then the foundation-model ARN. The
  # per-identifier grouping is not cosmetic — it is the order the dashboard renders, so
  # a customer comparing the two policies sees no difference to wonder about.
  #
  # `concat` of a possibly-empty tuple rather than a ternary between a 1-tuple and a
  # 2-tuple, which HCL will not unify.
  arn_specs = flatten([
    for id in local.profile_ids : concat(
      # The inference-profile ARN exists only for a geography-prefixed identifier: no
      # inference profile exists for a bare model id. It carries the configured region
      # and the customer's account id, and names the identifier IN FULL, geography
      # prefix included.
      [
        for geography in [local.geography_of[id]] : {
          region        = var.region
          account_id    = local.customer_account_id
          resource_type = local.arn_grammar.inferenceProfileResourceType
          resource_name = id
        } if geography != null
      ],
      # The foundation-model ARN always exists, and it is the one that carries a
      # wildcard: the geography's region wildcard when there is a geography prefix,
      # the configured region exactly when there is not. Its account field is EMPTY —
      # a foundation model is not owned by the caller's account.
      [
        {
          region = (local.geography_of[id] == null
            ? var.region
            : local.region_wildcards[local.geography_of[id]]
          )
          account_id    = local.arn_grammar.foundationModelAccountField
          resource_type = local.arn_grammar.foundationModelResourceType
          resource_name = local.model_id[id]
        }
      ],
    )
  ])

  # The grammar itself comes out of the file as a template with named placeholders,
  # so the shape of an ARN is not restated here either.
  invocation_resource_arns = [
    for spec in local.arn_specs :
    replace(replace(replace(replace(replace(replace(
      local.arn_grammar.template,
      "<partition>", local.arn_grammar.partition),
      "<service>", local.arn_grammar.service),
      "<region>", spec.region),
      "<accountId>", spec.account_id),
      "<resourceType>", spec.resource_type),
    "<resourceName>", spec.resource_name)
  ]

  # The prefix is not decoration. Soroush's inference principal is scoped to
  # `arn:aws:iam::*:role/soroush-inference-*` — the account field must be a wildcard
  # because customer account ids are unknown when Soroush deploys, but the role name
  # is not — so a role named anything else cannot be assumed at all. It is the only
  # additional mitigation available for a single shared principal: a compromised
  # principal can be pointed only at roles somebody deliberately named for Soroush.
  role_name = "soroush-inference-${var.soroush_account_id}"

  # The policy envelope — `Version`, `Effect`, and the single Action — is written here
  # rather than read from the file, which carries only what the ARNs are derived from.
  #
  # `bedrock:InvokeModel` and nothing else, which is every Bedrock action Soroush
  # exercises: it calls `Converse` non-streaming, which authorizes as
  # `bedrock:InvokeModel`. No `InvokeModelWithResponseStream`, no `bedrock:*`, and no
  # model-customization action — Soroush does not train, fine-tune, or distil on
  # customer data, and the absence of the permission is what enforces that rather than
  # a promise.
  permission_policy = {
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["bedrock:InvokeModel"]
        Resource = local.invocation_resource_arns
      },
    ]
  }

  # One statement, one principal, one action, one condition. Widening any of the four
  # is a finding, not a preference:
  #
  #   - a second principal, or a wildcard in `AWS`, hands the role to whoever else
  #     matches;
  #   - a missing `sts:ExternalId` condition makes the role assumable by anything
  #     Soroush's principal can reach, which is the confused-deputy problem the
  #     ExternalId exists to close;
  #   - `sts:AssumeRole` is the only action Soroush calls. Not `TagSession`, not
  #     `AssumeRoleWithWebIdentity`.
  #
  # `Action` is a bare string rather than a list, matching the policy the platform
  # publishes byte for byte, so a customer comparing the two sees no difference to
  # wonder about.
  trust_policy = {
    Version = "2012-10-17"
    Statement = [
      {
        Effect    = "Allow"
        Principal = { AWS = var.inference_principal_arn }
        Action    = "sts:AssumeRole"
        Condition = { StringEquals = { "sts:ExternalId" = var.external_id } }
      },
    ]
  }
}

# Read only when `customer_account_id` was not supplied. The `count` is what makes an
# offline plan possible: with the account id passed in, this data source is not read,
# so no STS call happens and `terraform plan` needs no credential.
data "aws_caller_identity" "current" {
  count = var.customer_account_id == null ? 1 : 0
}

resource "aws_iam_role" "inference" {
  name = local.role_name

  description = "Assumed by Soroush to run Bedrock inference for Soroush Account ${var.soroush_account_id} in this AWS account. Managed by the soroush inference-role Terraform module."

  assume_role_policy = jsonencode(local.trust_policy)

  # `path` is deliberately not set. The inference principal's policy is scoped to
  # `role/soroush-inference-*`, which does not match `role/some/path/soroush-inference-x`
  # — an IAM path would produce a role that satisfies the name prefix by eye and
  # cannot be assumed.

  # `max_session_duration` is left at the IAM default of 3600s. Soroush requests a
  # session of 900 seconds, or its generation timeout plus a margin if that is longer,
  # and that timeout defaults to 120 seconds, so the session always outlives the
  # request. Raising this grants nothing; lowering it below 900 is refused by STS
  # anyway.
}

# A separate `aws_iam_role_policy` rather than the role's `inline_policy` argument:
# `inline_policy` is deprecated in the AWS provider and takes exclusive management of
# every inline policy on the role, which would make this module fight anything else
# the customer attaches.
resource "aws_iam_role_policy" "invoke_model" {
  name   = "bedrock-invoke-model"
  role   = aws_iam_role.inference.id
  policy = jsonencode(local.permission_policy)
}
